num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
print("The first number is", num1)
print("The second number is", num2)
print("Sum of the numbers is", num1 + num2)